### ISSUE TITLE
大佬，想问一下，为什么要转成MP4片段，并且那一部分的代码真的完全看不懂，只能膜拜了

### ISSUE THREAD

**Issue by ChrisLee0211** [kekeqy/ke-rtsp#10]
我看好多网上的案例都是转m3u8的，然后用mse解析的，还有想问一下，空闲检测那里的逻辑，是怎么判断通道空闲的呢？我广州垃圾前端一枚，没太看懂，希望大佬有时间可以解释一下，谢谢啦。

**Comment by kekeqy** [comment]
m3u8的延迟比mp4要大很多，大概15s，mp4的延迟大概3s，前端也是用mse实现的，看示例demo。空闲检测是通过定时器去检测通道是否有客户端连接，如果无连接就说明是空闲。项目只是实现最基本的rtsp视频预览功能，实际运用还需自行加工。
