### ISSUE TITLE
在docker的Debian容器里无法转码

### ISSUE THREAD

**Issue by NidMo** [kekeqy/ke-rtsp#11]
在Debian的环境下，代码是能跑起来，但是spawn()方法执行的指令没生效，导致broadcast()方法也一直没执行，在windows环境下一切正常，能转码也能socket输出。

ffmpeg版本在两个环境下都是最新的

**Comment by kekeqy** [comment]
你直接用命令行运行一下ffmpeg，如果运行不了，请用命令把ffmpeg设置为可执行文件。
