### ISSUE TITLE
在对接完视频流后，可以播放几秒，随后执行_findMoof 方法时，报错

### ISSUE THREAD

**Issue by lubeiyi** [kekeqy/ke-rtsp#19]
nodejs调试控制台有如下报错：立即找不到moof！

**Comment by kekeqy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by kekeqy** [comment]
此项目已不再维护，如有需要可以使用我们的成熟流媒体软件nodenvr，1000元/套，文档地址[https://www.glowjs.com/docs/nodenvr/](https://www.glowjs.com/docs/nodenvr/)
