### ISSUE TITLE
延时问题

### ISSUE THREAD

**Issue by 823639792** [kekeqy/ke-rtsp#4]
你好，我按步骤，启动了服务器
但是视频的延时较高，有2.5秒的延时
关于延时，哪里可以设置下吗？可以进行优化吗？

还有一个问题，就是首屏的延时，出现画面大概要三四秒的时间，这个正常吗？能够设置吗？

**Comment by kekeqy** [comment]
延时是正常现象，因为播放用的是浏览器自带的解码库，自带的解码库一定有延迟，不同浏览器延迟还可能不尽相同。视频流其实已经实时到达了浏览器端，但是浏览器解码总是慢半拍。

**Comment by yinshangqing** [comment]
你好，按你的步骤来的，发现windwos下延时特别大，ubuntu下浏览器延时3秒左右，服务在windows下搭建的

**Comment by kekeqy** [comment]
特别大是多大？我windows系统一般延迟1~3秒，这都是可以接受的范围。

**Comment by yinshangqing** [comment]
![image](https://user-images.githubusercontent.com/26620006/56638779-96f64300-66a1-11e9-92e6-6fad81c0daed.png)
这个是同一时刻的，两个相差越来越大了

**Comment by yinshangqing** [comment]
这个15:24:44 的是在ubuntu下打开的，延时3到4秒，15:15:55延时就很大了

**Comment by 823639792** [comment]
有没有方案，能做到webrtc那样，毫秒级的延时？

**Comment by 823639792** [comment]
这么巧，我的摄像头前边也放了一盒药 @yinshangqing

**Comment by yinshangqing** [comment]
![image](https://user-images.githubusercontent.com/26620006/56639102-75498b80-66a2-11e9-8a1d-1e02cb6e9e29.png)
这个真的是在同一个环境下的

**Comment by yinshangqing** [comment]
@823639792 哈哈哈哈，那真的很巧呀

**Comment by kekeqy** [comment]
不一定是视频流存在延迟问题，更可能是html中的video标签存在延迟问题。在浏览器最小化的时候，video就停止播放了，但是视频却还在喂给video，浏览器最大化后video并不会自动从最新的位置进行播放，需要自己手动同步video的时间线。

**Comment by yinshangqing** [comment]
嗯嗯，我刚试了下，发现隐藏的时候，时间记住，再次打开的话，从上次的地方开始播放。好的，谢谢了

**Comment by kekeqy** [comment]
> 
> 
> 有没有方案，能做到webrtc那样，毫秒级的延时？

当然有方案，后端需要编码视频流，前端播放需要自己去解码视频流。比较耗硬件资源，但实时性很高。
