### ISSUE TITLE
视频没法播放声音，去掉video标签的muted会导致视频变成图片

### ISSUE THREAD

**Issue by wangxiaolong100** [kekeqy/ke-rtsp#5]
未实现视频播放还是bug?

**Comment by kekeqy** [comment]
后端封装视频流的时候默认把声音给去掉了。video标签的muted属性表示静音，只有设置了muted才能自动播放，否则会报错。

**Comment by qwe9527** [comment]
> 后端封装视频流的时候默认把声音给去掉了。video标签的muted属性表示静音，只有设置了muted才能自动播放，否则会报错。

后端怎么把声音加上

**Comment by kekeqy** [comment]
> > 后端封装视频流的时候默认把声音给去掉了。video标签的muted属性表示静音，只有设置了muted才能自动播放，否则会报错。
> 
> 后端怎么把声音加上

修改ffmpeg命令行参数
