### ISSUE TITLE
ffmpeg 怎么调试？

### ISSUE THREAD

**Issue by bananaCaptain** [kekeqy/ke-rtsp#7]
作者你好，请问在这个项目中怎么能看到ffmpeg的调试信息？感谢

**Comment by kekeqy** [comment]
需要修改2个地方。一是修改ffmpeg命令参数-loglevel的值，把quiet改成你需要的值，比如info。二是ffmpeg进程对象的stderr属性监听data事件，事件参数即为ffmpeg输出的日志信息。
