### ISSUE TITLE
Error:spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by YJH-Lab** [kekeqy/ke-rtsp#9]
请问这个错误应该怎么解决 是在node index.js启动的时候报错了。

**Comment by kekeqy** [comment]
你没有安装配置ffmpeg。

**Comment by YJH-Lab** [comment]
谢谢问题解决了

**Comment by jawis** [comment]
@kekeqy 你好，是要在本地下载后，node再安装吗？要是这样，项目布到网络环境，让用户使用怎么解决？

**Comment by jawis** [comment]
@yijiahui123 你好，请问你是怎么解决的，我是在node安装了ffmpeg  仍然报这个问题。

**Comment by YJH-Lab** [comment]
我当时是直接npm install ffmpeg，然后配置环境变量 在path中添加 “D:\安装路径\ffmpeg\bin”就可以使用了，我是window10系统@jawis

**Comment by jawis** [comment]
谢谢你，解决了。

**Comment by lolxy** [comment]
index.js:54 Error: spawn F:\recordingscreen\node_modules\electron\dist\resources\electron.asar\renderer\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267)
    at onErrorNT (internal/child_process.js:469)
    at processTicksAndRejections (internal/process/task_queues.js:84)
